schema: "classroom50/repo-config/v1"
classroom: "pm-class"
assignment: "js-map-filter"
owner:
  username: "danielshaji1"
  id: 232939717
  accepted_at: "2026-09-14T18:20:41Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "js-map-filter-c50"
  branch: "main"
