schema: "classroom50/repo-config/v1"
classroom: "pm-class"
assignment: "js-callbacks"
owner:
  username: "danielshaji1"
  id: 232939717
  accepted_at: "2026-09-22T17:54:09Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "js-callbacks-c50"
  branch: "main"
