schema: "classroom50/repo-config/v1"
classroom: "pm-class"
assignment: "js-functions"
owner:
  username: "danielshaji1"
  id: 232939717
  accepted_at: "2026-09-10T17:59:34Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "js-functionCalls"
  branch: "main"
